#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs =  " -r irb/completion"
libs <<  " -r #{File.dirname(__FILE__) + '/../lib/composite-ruby.rb'}"
puts "Loading composite-ruby gem"
exec "#{irb} #{libs} --simple-prompt"